// m6/vue/before/src/App.vue
<script setup lang="ts">

import { defineComponent, onMounted, reactive } from "vue";

// export default defineComponent({
//   setup() {

    const films = reactive(new Array<any>());

    onMounted(async () => {
      const result = await fetch(`https://bechdel.azurewebsites.net/api/films`);
      const json = await result.json();
      films.push(...json.results);
    });

//     return {
//       films
//     };
//   }
// })
</script>

<template>
  <div class="container">
    <h2>Results:</h2>
    <div id="results">
      <div v-for="film in films">
        <div class="film">
          <img class="" :src="film.posterUrl" :alt="film.title" />
          <div class="title">{{ film.title }}</div>
          <div>
            <div>{{ film.year }}</div>
            <div>
              <span class="">Rating:</span>
              {{ film.rating }}
            </div>
            <div>
              <span class="">Passed:</span>
              {{ film.passed }}
            </div>
            <div>
              <span class="">Reason:</span>
              {{ film.reason }}
            </div>
            <div>
              <span class="">Budget:</span>
              ${{ film.budget.toLocaleString("en-US") }}
            </div>
            <div>
              <span class="">Dom. Gross:</span>
              ${{ film.domesticGross.toLocaleString("en-US") }}
            </div>
            <div>
              <span class="">Int'l Gross:</span>
              ${{ film.internationalGross.toLocaleString("en-US") }}
            </div>
          </div>
          <p class="">{{ film.overview }}</p>
        </div>
      </div>
    </div>
  </div>
</template>

<style>
body {
  background-color: #888;
  margin: 0;
  padding: 0;
}
.container {
  width: 989px;
  margin: 0 auto;
  background-color: #eee;
  padding: .5rem;
}

#results {
  display: grid;
  grid-template-columns: 1fr 1fr 1fr;
  gap: 0.5rem;
  padding: 0.5rem;
}

#results .film {
  padding: 0.5rem;
  border: solid 1px #888;
  border-radius: 0.5rem;
}

#results .film .title {
  font-size: 1.2rem;
  font-weight: bold;
}
</style>

// m6/react/after/src/App.js
import React, { Component } from "react";
import "./App.css";

class App extends Component {
  constructor() {
    super();
    this.state = { data: [] };
  }

  async componentDidMount() {
    const response = await fetch(`https://bechdel.azurewebsites.net/api/films`);
    const json = await response.json();
    this.setState({ data: json.results });
  }

  render() {
    return (
      <div>
        <h1>Hello React</h1>
        <div id="results">
          {this.state.data.map((film) => (
            <div className="film" key={film.imdbId}>
              <img
                className="shadow-lg rounded float-right w-36"
                src={film.posterUrl}
                alt={film.title}
              />
              <div className="title">{film.title}</div>
              <div>
                <div>{film.year}</div>
                <div>
                  <span className="">Rating:</span>
                  {film.rating}
                </div>
                <div>
                  <span className="">Passed:</span>
                  {film.passed}
                </div>
                <div>
                  <span className="">Reason:</span>
                  {film.reason}
                </div>
                <div>
                  <span className="">Budget:</span>{" "}
                  $
                  {film.budget.toLocaleString("en-US")}
                </div>
                <div>
                  <span className="">
                    Dom. Gross:
                  </span>{" "}
                  $
                  {film.domesticGross.toLocaleString("en-US")}
                </div>
                <div>
                  <span className="">
                    Int'l Gross:
                  </span>{" "}
                  $
                  {film.internationalGross.toLocaleString("en-US")}
                </div>
              </div>
              <p className="text-sm p-1">{film.overview}</p>
            </div>
          ))}
        </div>
      </div>
    );
  }
}

export default App;
